server:
  port: 8080
  extend-address: 47.103.211.234

spring:
  application:
    name: im-service
  datasource:
    url: jdbc:mysql://${server.extend-address}:3306/im?useUnicode=true&characterEncoding=utf8&userSSL=false&serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  redis:
    sentinel:
      master: ${server.extend-address}:6379
      slave: ${server.extend-address}:6380,${server.extend-address}:6381
    password: 123456
    database: 0
    timeout: 5000
    max-active: 20
    max-wait: -1
    max-idle: 500
    min-idle: 0

chat:
  # 此程序的消费通道
  subTopic: im1
  # 全部通道
  allTopics: im1,im2

dataCenterId: 1
workerId: 1