spring:
  application:
    name: dubbo-leyou-user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10
    minIdle: 10
    maxActive: 20
    maxWait: 6000
    validationQuery: SELECT 1 FROM DUAL

dubbo:
  scan:
    base-packages: com.leyou.user.service.impl
  protocol:
    name: dubbo
    port: 11000
  registry:
    address: zookeeper://192.168.31.21:2181