spring:
  application:
    name: dubbo-leyou-user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10
    minIdle: 10
    maxActive: 20
    maxWait: 6000
    validationQuery: SELECT 1 FROM DUAL
  redis:
    sentinel:
      master: master
      nodes: 47.103.211.234:6379,47.103.211.234:6380,47.103.211.234:6381
    password: 123456

dubbo:
  scan:
    base-packages: com.leyou.goods.service.impl
  protocol:
    name: dubbo
    port: 12000
  registry:
    address: nacos://114.116.239.108:8848